### PR TITLE
feat: Add `avoid_consecutive_sliver_to_box_adapter` rule

### PR DESCRIPTION
**Pull request by naipaka**
## 🔗 Related Issues

- None

## 🙌 What's Done

- Add avoid sliver to box adapter

## ✍️ What's Not Done

- None

## 🖼️ Image Differences

CleanShot 2024-07-29 at 12 25 06

## 🤼 Desired Review Method

- [ ] Correction Commit
- [ ] Pair programming

> [!NOTE]
> It is possible that a reviewer's will may cause a method to be implemented that is not selected.

## Pre-launch Checklist
- [x] I have reviewed my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I updated/added relevant documentation (doc comments with ///).

### CODE REVIEW

**Review by k-nkmr — APPROVED** [review]
LGTM

**Comment by riscait** [comment]
badge
I was wondering if a SliverToBoxAdapter would be sufficient for elements such as a heading string in the sense of using a TextWidget in a Column?
With this rule in place, this...

```dart
SliverToBoxAdapter(child: HEADER_WIDGET),
SliverList.builder(itemBuilder: LOTS_OF_CONTENTS)
```

This...

```dart
SliverList.list(children: [HEADER_WIDGET]),
SliverList.builder(itemBuilder: LOTS_OF_CONTENTS)
```

Do I need to write it like this?
I asked if I could write the above!

If the data is drawn all at once, it is the same as when columns are used, so I thought there would not be much of a performance problem unless it is used to display a large amount of data.
I am concerned about the fact that SliverList must be used even though it is not a List.

**Comment by riscait** [comment]
Instead, would a rule like "do not use `Column` as a child of `SliverToBoxAdapter`" be a good idea?

**Comment by naipaka** [comment]
@riscait 
Thank you for your valuable input!
Based on the feedback and discussion, I have modified it to issue a warning if `SliverToBoxAdapter` is used consecutively!

Please review and confirm 🙇‍♂️

When `SliverToBoxAdapter` is consecutive:
CleanShot 2024-07-29 at 17 36 53

When `SliverToBoxAdapter` is consecutive and wrapped in `SliverPadding`:
CleanShot 2024-07-29 at 17 37 03

When `SliverToBoxAdapter` is not consecutive:
CleanShot 2024-07-29 at 17 37 10

**Review by riscait — APPROVED** [review]
LGTM
Excellent response! Perfect, thank you!

**Pull request merged**
