### PR TITLE
feat: Add `prefer_sliver_prefix` rule

### PR DESCRIPTION
**Pull request by naipaka**
## 🔗 Related Issues

- None

## 🙌 What's Done

- Add `prefer_sliver_prefix` rule

## ✍️ What's Not Done

- None

## 🖼️ Image Differences

CleanShot 2024-07-29 at 18 04 32

## 🤼 Desired Review Method

- [ ] Correction Commit
- [ ] Pair programming

> [!NOTE]
> It is possible that a reviewer's will may cause a method to be implemented that is not selected.

## 📝 Additional Notes

This rule ensures that class names are consistent and easily recognizable as returning a Sliver widget!

## Pre-launch Checklist
- [x] I have reviewed my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I updated/added relevant documentation (doc comments with ///).

### CODE REVIEW

**Review by riscait — APPROVED** [review]
LGTM
This is another great rule!

badge
Would a rule like "prefer_to_include_sliver_in_name" be better so that it is not limited to Prefix?
example: `MyWidget.sliver()` , `MyExcellentViewWithSliver()` , `AltiveSliverWidget()` .

**Comment by naipaka** [comment]
@riscait 
> Would a rule like "prefer_to_include_sliver_in_name" be better so that it is not limited to Prefix?
example: MyWidget.sliver() , MyExcellentViewWithSliver() , AltiveSliverWidget() .

Indeed, having some flexibility might be beneficial✍️

Including the constructor could result in significant changes, so how about creating a separate improvement issue and having someone else handle it? 💭

**Comment by riscait** [comment]
> Including the constructor could result in significant changes, so how about creating a separate improvement issue and having someone else handle it? 💭

Let's do that!

**Comment by naipaka** [comment]
I created the following issue!
https://github.com/altive/altive_lints/issues/36

**Pull request merged**
